/**
 * Copy for the transactional e-mails customers must understand (order
 * confirmation, video delivery, abandoned cart), in every storefront locale.
 * Orders record their locale since October 2026; older orders fall back to
 * English. Marketing e-mails are still English-only.
 */

export type EmailCopy = {
  confirmSubject: string;
  confirmTitle: string;
  confirmIntro: string;
  details: string;
  orderRef: string;
  date: string;
  total: string;
  delivery: string;
  deliveryStandard: string;
  deliveryExpress: string;
  music: string;
  musicCustom: string;
  musicDefault: string;
  musicLink: string;
  danceExtended: string;
  yes: string;
  message: string;
  confirmOutro: string;
  help: string;
  videoSubject: string;
  hi: string;
  videoReady: string;
  videoCta: string;
  videoFallback: string;
  videoReference: string;
  thanks: string;
  team: string;
  footerTagline: string;
  footerReason: string;
  cartSubject: string;
  cartBody: string;
  cartCta: string;
};

const COPY: Record<string, EmailCopy> = {
  en: {
    confirmSubject: "Your AfroBirthday order is confirmed ({ref})",
    confirmTitle: "Thanks for your order 🎂",
    confirmIntro: "We received your order and your payment. Our dancers are getting ready!",
    details: "Order details",
    orderRef: "Order",
    date: "Date",
    total: "Total",
    delivery: "Delivery",
    deliveryStandard: "Standard (24–48 h)",
    deliveryExpress: "Express (12–24 h)",
    music: "Music",
    musicCustom: "Your song",
    musicDefault: "Chosen by us",
    musicLink: "Song link",
    danceExtended: "Extended dance version",
    yes: "Yes",
    message: "Your message",
    confirmOutro: "You'll receive your video by email as soon as it's ready.",
    help: "Need help? Just reply to this email.",
    videoSubject: "Your AfroBirthday video is ready 🎉 ({ref})",
    hi: "Hi,",
    videoReady: "Your personalized birthday video is ready. You can watch and download it here:",
    videoCta: "Watch my video",
    videoFallback: "If the button doesn't open, copy this link into your browser:",
    videoReference: "Order reference: {ref}. We'd love your feedback — just reply to this email.",
    thanks: "Thanks for choosing AfroBirthday,",
    team: "The AfroBirthday team",
    footerTagline: "AfroBirthday — Personalized birthday videos",
    footerReason: "You're receiving this email because you placed an order on afrobirthday.com.",
    cartSubject: "Your birthday video is waiting 🎂",
    cartBody: "You started a personalized birthday video but didn't finish your order. Pick up right where you left off:",
    cartCta: "Finish my order",
  },
  fr: {
    confirmSubject: "Votre commande AfroBirthday est confirmée ({ref})",
    confirmTitle: "Merci pour votre commande 🎂",
    confirmIntro: "Nous avons bien reçu votre commande et votre paiement. Nos danseurs se préparent !",
    details: "Détails de la commande",
    orderRef: "Commande",
    date: "Date",
    total: "Total",
    delivery: "Livraison",
    deliveryStandard: "Standard (24–48 h)",
    deliveryExpress: "Express (12–24 h)",
    music: "Musique",
    musicCustom: "Votre chanson",
    musicDefault: "Choisie par nous",
    musicLink: "Lien de la chanson",
    danceExtended: "Version danse longue",
    yes: "Oui",
    message: "Votre message",
    confirmOutro: "Vous recevrez votre vidéo par e-mail dès qu'elle sera prête.",
    help: "Une question ? Répondez simplement à cet e-mail.",
    videoSubject: "Votre vidéo AfroBirthday est prête 🎉 ({ref})",
    hi: "Bonjour,",
    videoReady: "Votre vidéo d'anniversaire personnalisée est prête. Vous pouvez la regarder et la télécharger ici :",
    videoCta: "Voir ma vidéo",
    videoFallback: "Si le bouton ne s'ouvre pas, copiez ce lien dans votre navigateur :",
    videoReference: "Référence de commande : {ref}. Votre avis nous intéresse — répondez simplement à cet e-mail.",
    thanks: "Merci d'avoir choisi AfroBirthday,",
    team: "L'équipe AfroBirthday",
    footerTagline: "AfroBirthday — Vidéos d'anniversaire personnalisées",
    footerReason: "Vous recevez cet e-mail suite à votre commande sur afrobirthday.com.",
    cartSubject: "Votre vidéo d'anniversaire vous attend 🎂",
    cartBody: "Vous avez commencé une vidéo d'anniversaire personnalisée sans finaliser votre commande. Reprenez là où vous vous étiez arrêté :",
    cartCta: "Finaliser ma commande",
  },
  es: {
    confirmSubject: "Tu pedido de AfroBirthday está confirmado ({ref})",
    confirmTitle: "Gracias por tu pedido 🎂",
    confirmIntro: "Hemos recibido tu pedido y tu pago. ¡Nuestros bailarines se están preparando!",
    details: "Detalles del pedido",
    orderRef: "Pedido",
    date: "Fecha",
    total: "Total",
    delivery: "Entrega",
    deliveryStandard: "Estándar (24–48 h)",
    deliveryExpress: "Exprés (12–24 h)",
    music: "Música",
    musicCustom: "Tu canción",
    musicDefault: "Elegida por nosotros",
    musicLink: "Enlace de la canción",
    danceExtended: "Versión de baile extendida",
    yes: "Sí",
    message: "Tu mensaje",
    confirmOutro: "Recibirás tu vídeo por email en cuanto esté listo.",
    help: "¿Necesitas ayuda? Responde a este email.",
    videoSubject: "Tu vídeo de AfroBirthday está listo 🎉 ({ref})",
    hi: "Hola,",
    videoReady: "Tu vídeo de cumpleaños personalizado está listo. Puedes verlo y descargarlo aquí:",
    videoCta: "Ver mi vídeo",
    videoFallback: "Si el botón no se abre, copia este enlace en tu navegador:",
    videoReference: "Referencia del pedido: {ref}. Nos encantaría saber tu opinión — responde a este email.",
    thanks: "Gracias por elegir AfroBirthday,",
    team: "El equipo de AfroBirthday",
    footerTagline: "AfroBirthday — Vídeos de cumpleaños personalizados",
    footerReason: "Recibes este email porque hiciste un pedido en afrobirthday.com.",
    cartSubject: "Tu vídeo de cumpleaños te espera 🎂",
    cartBody: "Empezaste un vídeo de cumpleaños personalizado pero no terminaste tu pedido. Continúa donde lo dejaste:",
    cartCta: "Terminar mi pedido",
  },
  de: {
    confirmSubject: "Deine AfroBirthday-Bestellung ist bestätigt ({ref})",
    confirmTitle: "Danke für deine Bestellung 🎂",
    confirmIntro: "Wir haben deine Bestellung und deine Zahlung erhalten. Unsere Tänzer machen sich bereit!",
    details: "Bestelldetails",
    orderRef: "Bestellung",
    date: "Datum",
    total: "Gesamt",
    delivery: "Lieferung",
    deliveryStandard: "Standard (24–48 Std.)",
    deliveryExpress: "Express (12–24 Std.)",
    music: "Musik",
    musicCustom: "Dein Song",
    musicDefault: "Von uns ausgewählt",
    musicLink: "Song-Link",
    danceExtended: "Verlängerte Tanzversion",
    yes: "Ja",
    message: "Deine Nachricht",
    confirmOutro: "Du erhältst dein Video per E-Mail, sobald es fertig ist.",
    help: "Fragen? Antworte einfach auf diese E-Mail.",
    videoSubject: "Dein AfroBirthday-Video ist fertig 🎉 ({ref})",
    hi: "Hallo,",
    videoReady: "Dein personalisiertes Geburtstagsvideo ist fertig. Hier kannst du es ansehen und herunterladen:",
    videoCta: "Mein Video ansehen",
    videoFallback: "Falls der Button nicht funktioniert, kopiere diesen Link in deinen Browser:",
    videoReference: "Bestellnummer: {ref}. Wir freuen uns über dein Feedback — antworte einfach auf diese E-Mail.",
    thanks: "Danke, dass du AfroBirthday gewählt hast,",
    team: "Dein AfroBirthday-Team",
    footerTagline: "AfroBirthday — Personalisierte Geburtstagsvideos",
    footerReason: "Du erhältst diese E-Mail, weil du auf afrobirthday.com bestellt hast.",
    cartSubject: "Dein Geburtstagsvideo wartet auf dich 🎂",
    cartBody: "Du hast ein personalisiertes Geburtstagsvideo begonnen, aber die Bestellung nicht abgeschlossen. Mach genau dort weiter:",
    cartCta: "Bestellung abschließen",
  },
  it: {
    confirmSubject: "Il tuo ordine AfroBirthday è confermato ({ref})",
    confirmTitle: "Grazie per il tuo ordine 🎂",
    confirmIntro: "Abbiamo ricevuto il tuo ordine e il pagamento. I nostri ballerini si stanno preparando!",
    details: "Dettagli dell'ordine",
    orderRef: "Ordine",
    date: "Data",
    total: "Totale",
    delivery: "Consegna",
    deliveryStandard: "Standard (24–48 ore)",
    deliveryExpress: "Express (12–24 ore)",
    music: "Musica",
    musicCustom: "La tua canzone",
    musicDefault: "Scelta da noi",
    musicLink: "Link della canzone",
    danceExtended: "Versione ballo estesa",
    yes: "Sì",
    message: "Il tuo messaggio",
    confirmOutro: "Riceverai il video via email non appena sarà pronto.",
    help: "Hai bisogno di aiuto? Rispondi a questa email.",
    videoSubject: "Il tuo video AfroBirthday è pronto 🎉 ({ref})",
    hi: "Ciao,",
    videoReady: "Il tuo video di compleanno personalizzato è pronto. Puoi guardarlo e scaricarlo qui:",
    videoCta: "Guarda il mio video",
    videoFallback: "Se il pulsante non si apre, copia questo link nel browser:",
    videoReference: "Riferimento ordine: {ref}. Ci farebbe piacere un tuo parere — rispondi a questa email.",
    thanks: "Grazie per aver scelto AfroBirthday,",
    team: "Il team AfroBirthday",
    footerTagline: "AfroBirthday — Video di compleanno personalizzati",
    footerReason: "Ricevi questa email perché hai effettuato un ordine su afrobirthday.com.",
    cartSubject: "Il tuo video di compleanno ti aspetta 🎂",
    cartBody: "Hai iniziato un video di compleanno personalizzato ma non hai completato l'ordine. Riprendi da dove avevi lasciato:",
    cartCta: "Completa il mio ordine",
  },
  pt: {
    confirmSubject: "A sua encomenda AfroBirthday está confirmada ({ref})",
    confirmTitle: "Obrigado pela sua encomenda 🎂",
    confirmIntro: "Recebemos a sua encomenda e o pagamento. Os nossos dançarinos estão a preparar-se!",
    details: "Detalhes da encomenda",
    orderRef: "Encomenda",
    date: "Data",
    total: "Total",
    delivery: "Entrega",
    deliveryStandard: "Normal (24–48 h)",
    deliveryExpress: "Expresso (12–24 h)",
    music: "Música",
    musicCustom: "A sua música",
    musicDefault: "Escolhida por nós",
    musicLink: "Link da música",
    danceExtended: "Versão de dança alargada",
    yes: "Sim",
    message: "A sua mensagem",
    confirmOutro: "Vai receber o vídeo por email assim que estiver pronto.",
    help: "Precisa de ajuda? Basta responder a este email.",
    videoSubject: "O seu vídeo AfroBirthday está pronto 🎉 ({ref})",
    hi: "Olá,",
    videoReady: "O seu vídeo de aniversário personalizado está pronto. Pode vê-lo e descarregá-lo aqui:",
    videoCta: "Ver o meu vídeo",
    videoFallback: "Se o botão não abrir, copie este link para o navegador:",
    videoReference: "Referência da encomenda: {ref}. Adorávamos saber a sua opinião — responda a este email.",
    thanks: "Obrigado por escolher a AfroBirthday,",
    team: "A equipa AfroBirthday",
    footerTagline: "AfroBirthday — Vídeos de aniversário personalizados",
    footerReason: "Recebe este email porque fez uma encomenda em afrobirthday.com.",
    cartSubject: "O seu vídeo de aniversário está à espera 🎂",
    cartBody: "Começou um vídeo de aniversário personalizado mas não concluiu a encomenda. Continue onde parou:",
    cartCta: "Concluir a encomenda",
  },
  nl: {
    confirmSubject: "Je AfroBirthday-bestelling is bevestigd ({ref})",
    confirmTitle: "Bedankt voor je bestelling 🎂",
    confirmIntro: "We hebben je bestelling en betaling ontvangen. Onze dansers maken zich klaar!",
    details: "Bestelgegevens",
    orderRef: "Bestelling",
    date: "Datum",
    total: "Totaal",
    delivery: "Levering",
    deliveryStandard: "Standaard (24–48 uur)",
    deliveryExpress: "Express (12–24 uur)",
    music: "Muziek",
    musicCustom: "Jouw nummer",
    musicDefault: "Door ons gekozen",
    musicLink: "Link naar het nummer",
    danceExtended: "Verlengde dansversie",
    yes: "Ja",
    message: "Jouw bericht",
    confirmOutro: "Je ontvangt je video per e-mail zodra hij klaar is.",
    help: "Vragen? Beantwoord gewoon deze e-mail.",
    videoSubject: "Je AfroBirthday-video is klaar 🎉 ({ref})",
    hi: "Hallo,",
    videoReady: "Je persoonlijke verjaardagsvideo is klaar. Bekijk en download hem hier:",
    videoCta: "Bekijk mijn video",
    videoFallback: "Werkt de knop niet? Kopieer deze link in je browser:",
    videoReference: "Bestelnummer: {ref}. We horen graag wat je ervan vindt — beantwoord gewoon deze e-mail.",
    thanks: "Bedankt voor je keuze voor AfroBirthday,",
    team: "Het AfroBirthday-team",
    footerTagline: "AfroBirthday — Persoonlijke verjaardagsvideo's",
    footerReason: "Je ontvangt deze e-mail omdat je hebt besteld op afrobirthday.com.",
    cartSubject: "Je verjaardagsvideo wacht op je 🎂",
    cartBody: "Je bent begonnen aan een persoonlijke verjaardagsvideo maar hebt je bestelling niet afgerond. Ga verder waar je gebleven was:",
    cartCta: "Bestelling afronden",
  },
  ar: {
    confirmSubject: "تم تأكيد طلبك من AfroBirthday ({ref})",
    confirmTitle: "شكرًا لطلبك 🎂",
    confirmIntro: "استلمنا طلبك ودفعتك. راقصونا يستعدون الآن!",
    details: "تفاصيل الطلب",
    orderRef: "الطلب",
    date: "التاريخ",
    total: "الإجمالي",
    delivery: "التسليم",
    deliveryStandard: "عادي (24–48 ساعة)",
    deliveryExpress: "سريع (12–24 ساعة)",
    music: "الموسيقى",
    musicCustom: "أغنيتك",
    musicDefault: "من اختيارنا",
    musicLink: "رابط الأغنية",
    danceExtended: "نسخة رقص مطوّلة",
    yes: "نعم",
    message: "رسالتك",
    confirmOutro: "ستصلك الفيديو عبر البريد الإلكتروني فور جهوزه.",
    help: "تحتاج مساعدة؟ رد على هذه الرسالة.",
    videoSubject: "فيديو AfroBirthday الخاص بك جاهز 🎉 ({ref})",
    hi: "مرحبًا،",
    videoReady: "فيديو عيد الميلاد المخصص لك جاهز. يمكنك مشاهدته وتنزيله من هنا:",
    videoCta: "شاهد الفيديو",
    videoFallback: "إذا لم يعمل الزر، انسخ هذا الرابط في متصفحك:",
    videoReference: "رقم الطلب: {ref}. يسعدنا سماع رأيك — رد على هذه الرسالة.",
    thanks: "شكرًا لاختيارك AfroBirthday،",
    team: "فريق AfroBirthday",
    footerTagline: "AfroBirthday — فيديوهات أعياد ميلاد مخصصة",
    footerReason: "تتلقى هذه الرسالة لأنك قمت بطلب على afrobirthday.com.",
    cartSubject: "فيديو عيد الميلاد بانتظارك 🎂",
    cartBody: "بدأت إنشاء فيديو عيد ميلاد مخصص لكنك لم تُكمل طلبك. تابع من حيث توقفت:",
    cartCta: "إكمال طلبي",
  },
  hi: {
    confirmSubject: "आपका AfroBirthday ऑर्डर कन्फ़र्म हो गया ({ref})",
    confirmTitle: "आपके ऑर्डर के लिए धन्यवाद 🎂",
    confirmIntro: "हमें आपका ऑर्डर और भुगतान मिल गया है। हमारे डांसर तैयारी कर रहे हैं!",
    details: "ऑर्डर विवरण",
    orderRef: "ऑर्डर",
    date: "तारीख",
    total: "कुल",
    delivery: "डिलीवरी",
    deliveryStandard: "स्टैंडर्ड (24–48 घंटे)",
    deliveryExpress: "एक्सप्रेस (12–24 घंटे)",
    music: "संगीत",
    musicCustom: "आपका गाना",
    musicDefault: "हमारे द्वारा चुना गया",
    musicLink: "गाने का लिंक",
    danceExtended: "लंबा डांस वर्ज़न",
    yes: "हाँ",
    message: "आपका संदेश",
    confirmOutro: "वीडियो तैयार होते ही आपको ईमेल से मिल जाएगा।",
    help: "मदद चाहिए? बस इस ईमेल का जवाब दें।",
    videoSubject: "आपका AfroBirthday वीडियो तैयार है 🎉 ({ref})",
    hi: "नमस्ते,",
    videoReady: "आपका पर्सनलाइज़्ड जन्मदिन वीडियो तैयार है। आप इसे यहाँ देख और डाउनलोड कर सकते हैं:",
    videoCta: "मेरा वीडियो देखें",
    videoFallback: "अगर बटन न खुले, तो यह लिंक अपने ब्राउज़र में कॉपी करें:",
    videoReference: "ऑर्डर संदर्भ: {ref}. हमें आपकी राय जानकर खुशी होगी — बस इस ईमेल का जवाब दें।",
    thanks: "AfroBirthday चुनने के लिए धन्यवाद,",
    team: "AfroBirthday टीम",
    footerTagline: "AfroBirthday — पर्सनलाइज़्ड जन्मदिन वीडियो",
    footerReason: "आपको यह ईमेल इसलिए मिला क्योंकि आपने afrobirthday.com पर ऑर्डर किया था।",
    cartSubject: "आपका जन्मदिन वीडियो इंतज़ार कर रहा है 🎂",
    cartBody: "आपने एक पर्सनलाइज़्ड जन्मदिन वीडियो शुरू किया था लेकिन ऑर्डर पूरा नहीं किया। वहीं से जारी रखें:",
    cartCta: "मेरा ऑर्डर पूरा करें",
  },
  zh: {
    confirmSubject: "您的 AfroBirthday 订单已确认（{ref}）",
    confirmTitle: "感谢您的订单 🎂",
    confirmIntro: "我们已收到您的订单和付款。舞者们正在准备！",
    details: "订单详情",
    orderRef: "订单",
    date: "日期",
    total: "合计",
    delivery: "交付",
    deliveryStandard: "标准（24–48 小时）",
    deliveryExpress: "加急（12–24 小时）",
    music: "音乐",
    musicCustom: "您的歌曲",
    musicDefault: "由我们挑选",
    musicLink: "歌曲链接",
    danceExtended: "加长舞蹈版",
    yes: "是",
    message: "您的留言",
    confirmOutro: "视频完成后会第一时间通过电子邮件发送给您。",
    help: "需要帮助？直接回复此邮件即可。",
    videoSubject: "您的 AfroBirthday 视频已完成 🎉（{ref}）",
    hi: "您好，",
    videoReady: "您的专属生日视频已完成，可在此观看和下载：",
    videoCta: "观看我的视频",
    videoFallback: "如果按钮无法打开，请将此链接复制到浏览器：",
    videoReference: "订单编号：{ref}。欢迎反馈意见——直接回复此邮件即可。",
    thanks: "感谢您选择 AfroBirthday，",
    team: "AfroBirthday 团队",
    footerTagline: "AfroBirthday — 专属生日视频",
    footerReason: "您收到此邮件是因为您在 afrobirthday.com 下了订单。",
    cartSubject: "您的生日视频还在等您 🎂",
    cartBody: "您开始制作专属生日视频，但尚未完成订单。从上次离开的地方继续：",
    cartCta: "完成我的订单",
  },
};

export function emailLocale(order: { locale?: string | null }): string {
  return order.locale && COPY[order.locale] ? order.locale : "en";
}

export function emailCopy(order: { locale?: string | null }): EmailCopy {
  return COPY[emailLocale(order)];
}

export function fill(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? "");
}
