/**
 * Copy for the transactional e-mails customers must understand (order
 * confirmation, video delivery, abandoned cart), in every storefront locale.
 * Orders record their locale since October 2026; older orders fall back to
 * English. Marketing e-mails (review, cross-sell, annual reminder, referral)
 * use the same copy since October 2026.
 */

export type EmailCopy = {
  confirmSubject: string;
  confirmTitle: string;
  confirmIntro: string;
  details: string;
  orderRef: string;
  date: string;
  total: string;
  delivery: string;
  deliveryStandard: string;
  deliveryExpress: string;
  music: string;
  musicCustom: string;
  musicDefault: string;
  musicLink: string;
  danceExtended: string;
  yes: string;
  message: string;
  confirmOutro: string;
  help: string;
  videoSubject: string;
  hi: string;
  videoReady: string;
  videoCta: string;
  videoFallback: string;
  videoReference: string;
  thanks: string;
  team: string;
  footerTagline: string;
  footerReason: string;
  cartSubject: string;
  cartBody: string;
  cartCta: string;
  unsubscribe: string;
  promoCodeLabel: string;
  discountPercent: string;
  discountFixed: string;
  reviewSubject: string;
  reviewBody: string;
  reviewCta: string;
  crossSellSubject: string;
  crossSellBody: string;
  crossSellCta: string;
  annualSubject: string;
  annualBody: string;
  annualCta: string;
  referralSubject: string;
  referralBody: string;
  referralLinkIntro: string;
  referralCodeLabel: string;
  referralRewardSubject: string;
  referralRewardBody: string;
};

const COPY: Record<string, EmailCopy> = {
  en: {
    confirmSubject: "Your AfroBirthday order is confirmed ({ref})",
    confirmTitle: "Thanks for your order 🎂",
    confirmIntro: "We received your order and your payment. Our dancers are getting ready!",
    details: "Order details",
    orderRef: "Order",
    date: "Date",
    total: "Total",
    delivery: "Delivery",
    deliveryStandard: "Standard (24–48 h)",
    deliveryExpress: "Express (12–24 h)",
    music: "Music",
    musicCustom: "Your song",
    musicDefault: "Chosen by us",
    musicLink: "Song link",
    danceExtended: "Extended dance version",
    yes: "Yes",
    message: "Your message",
    confirmOutro: "You'll receive your video by email as soon as it's ready.",
    help: "Need help? Just reply to this email.",
    videoSubject: "Your AfroBirthday video is ready 🎉 ({ref})",
    hi: "Hi,",
    videoReady: "Your personalized birthday video is ready. You can watch and download it here:",
    videoCta: "Watch my video",
    videoFallback: "If the button doesn't open, copy this link into your browser:",
    videoReference: "Order reference: {ref}. We'd love your feedback — just reply to this email.",
    thanks: "Thanks for choosing AfroBirthday,",
    team: "The AfroBirthday team",
    footerTagline: "AfroBirthday — Personalized birthday videos",
    footerReason: "You're receiving this email because you placed an order on afrobirthday.com.",
    cartSubject: "Your birthday video is waiting 🎂",
    cartBody: "You started a personalized birthday video but didn't finish your order. Pick up right where you left off:",
    cartCta: "Finish my order",
    unsubscribe: "Unsubscribe from these emails",
    promoCodeLabel: "Your code",
    discountPercent: "{value}% off",
    discountFixed: "${value} off",
    reviewSubject: "How was your AfroBirthday video?",
    reviewBody: "We hope you loved your personalized birthday video! If you have a minute, a quick review would mean a lot — it helps other people discover us.",
    reviewCta: "Leave a review on Trustpilot",
    crossSellSubject: "Another birthday coming up?",
    crossSellBody: "Got another birthday coming up? Surprise someone else with a personalized AfroBirthday video — your code below gives you a discount, and it applies itself when you use the button.",
    crossSellCta: "Order another video",
    annualSubject: "Same celebration this year?",
    annualBody: "It's been a year since your AfroBirthday video — same celebration again this year? Here's a code to make it easy; it applies itself when you use the button.",
    annualCta: "Start my next video",
    referralSubject: "Share the surprise, get rewarded",
    referralBody: "Loved your AfroBirthday video? Share it with friends: your personal code gives them {discount} on their first order. When they use it, we'll send you a reward too.",
    referralLinkIntro: "Or just send them this link — the code applies itself:",
    referralCodeLabel: "Your referral code",
    referralRewardSubject: "A friend used your referral code!",
    referralRewardBody: "Good news — a friend just used your referral code! As a thank you, here's {discount} on your next AfroBirthday video.",
  },
  fr: {
    confirmSubject: "Votre commande AfroBirthday est confirmée ({ref})",
    confirmTitle: "Merci pour votre commande 🎂",
    confirmIntro: "Nous avons bien reçu votre commande et votre paiement. Nos danseurs se préparent !",
    details: "Détails de la commande",
    orderRef: "Commande",
    date: "Date",
    total: "Total",
    delivery: "Livraison",
    deliveryStandard: "Standard (24–48 h)",
    deliveryExpress: "Express (12–24 h)",
    music: "Musique",
    musicCustom: "Votre chanson",
    musicDefault: "Choisie par nous",
    musicLink: "Lien de la chanson",
    danceExtended: "Version danse longue",
    yes: "Oui",
    message: "Votre message",
    confirmOutro: "Vous recevrez votre vidéo par e-mail dès qu'elle sera prête.",
    help: "Une question ? Répondez simplement à cet e-mail.",
    videoSubject: "Votre vidéo AfroBirthday est prête 🎉 ({ref})",
    hi: "Bonjour,",
    videoReady: "Votre vidéo d'anniversaire personnalisée est prête. Vous pouvez la regarder et la télécharger ici :",
    videoCta: "Voir ma vidéo",
    videoFallback: "Si le bouton ne s'ouvre pas, copiez ce lien dans votre navigateur :",
    videoReference: "Référence de commande : {ref}. Votre avis nous intéresse — répondez simplement à cet e-mail.",
    thanks: "Merci d'avoir choisi AfroBirthday,",
    team: "L'équipe AfroBirthday",
    footerTagline: "AfroBirthday — Vidéos d'anniversaire personnalisées",
    footerReason: "Vous recevez cet e-mail suite à votre commande sur afrobirthday.com.",
    cartSubject: "Votre vidéo d'anniversaire vous attend 🎂",
    cartBody: "Vous avez commencé une vidéo d'anniversaire personnalisée sans finaliser votre commande. Reprenez là où vous vous étiez arrêté :",
    cartCta: "Finaliser ma commande",
    unsubscribe: "Se désabonner de ces e-mails",
    promoCodeLabel: "Votre code",
    discountPercent: "{value} % de réduction",
    discountFixed: "{value} $ de réduction",
    reviewSubject: "Votre vidéo AfroBirthday vous a plu ?",
    reviewBody: "Nous espérons que votre vidéo d'anniversaire vous a plu ! Si vous avez une minute, un petit avis nous aiderait beaucoup : il permet à d'autres de nous découvrir.",
    reviewCta: "Laisser un avis sur Trustpilot",
    crossSellSubject: "Un autre anniversaire bientôt ?",
    crossSellBody: "Un autre anniversaire approche ? Faites une nouvelle surprise avec une vidéo AfroBirthday personnalisée : votre code ci-dessous vous offre une réduction, appliquée automatiquement avec le bouton.",
    crossSellCta: "Commander une autre vidéo",
    annualSubject: "On remet ça cette année ?",
    annualBody: "Cela fait un an que vous avez commandé votre vidéo AfroBirthday : on fête à nouveau cette année ? Voici un code pour vous simplifier la vie, appliqué automatiquement avec le bouton.",
    annualCta: "Créer ma prochaine vidéo",
    referralSubject: "Partagez la surprise, soyez récompensé",
    referralBody: "Votre vidéo AfroBirthday vous a plu ? Partagez-la : votre code personnel offre {discount} à vos proches sur leur première commande. Quand ils l'utilisent, vous recevez aussi une récompense.",
    referralLinkIntro: "Ou envoyez-leur simplement ce lien, le code s'applique tout seul :",
    referralCodeLabel: "Votre code de parrainage",
    referralRewardSubject: "Un proche a utilisé votre code de parrainage !",
    referralRewardBody: "Bonne nouvelle : un proche vient d'utiliser votre code de parrainage ! Pour vous remercier, voici {discount} sur votre prochaine vidéo AfroBirthday.",
  },
  es: {
    confirmSubject: "Tu pedido de AfroBirthday está confirmado ({ref})",
    confirmTitle: "Gracias por tu pedido 🎂",
    confirmIntro: "Hemos recibido tu pedido y tu pago. ¡Nuestros bailarines se están preparando!",
    details: "Detalles del pedido",
    orderRef: "Pedido",
    date: "Fecha",
    total: "Total",
    delivery: "Entrega",
    deliveryStandard: "Estándar (24–48 h)",
    deliveryExpress: "Exprés (12–24 h)",
    music: "Música",
    musicCustom: "Tu canción",
    musicDefault: "Elegida por nosotros",
    musicLink: "Enlace de la canción",
    danceExtended: "Versión de baile extendida",
    yes: "Sí",
    message: "Tu mensaje",
    confirmOutro: "Recibirás tu vídeo por email en cuanto esté listo.",
    help: "¿Necesitas ayuda? Responde a este email.",
    videoSubject: "Tu vídeo de AfroBirthday está listo 🎉 ({ref})",
    hi: "Hola,",
    videoReady: "Tu vídeo de cumpleaños personalizado está listo. Puedes verlo y descargarlo aquí:",
    videoCta: "Ver mi vídeo",
    videoFallback: "Si el botón no se abre, copia este enlace en tu navegador:",
    videoReference: "Referencia del pedido: {ref}. Nos encantaría saber tu opinión — responde a este email.",
    thanks: "Gracias por elegir AfroBirthday,",
    team: "El equipo de AfroBirthday",
    footerTagline: "AfroBirthday — Vídeos de cumpleaños personalizados",
    footerReason: "Recibes este email porque hiciste un pedido en afrobirthday.com.",
    cartSubject: "Tu vídeo de cumpleaños te espera 🎂",
    cartBody: "Empezaste un vídeo de cumpleaños personalizado pero no terminaste tu pedido. Continúa donde lo dejaste:",
    cartCta: "Terminar mi pedido",
    unsubscribe: "Darse de baja de estos correos",
    promoCodeLabel: "Tu código",
    discountPercent: "{value} % de descuento",
    discountFixed: "{value} $ de descuento",
    reviewSubject: "¿Qué te pareció tu video de AfroBirthday?",
    reviewBody: "¡Esperamos que te haya encantado tu video de cumpleaños! Si tienes un minuto, una reseña rápida nos ayudaría mucho: así otras personas nos descubren.",
    reviewCta: "Dejar una reseña en Trustpilot",
    crossSellSubject: "¿Se acerca otro cumpleaños?",
    crossSellBody: "¿Se acerca otro cumpleaños? Sorprende a alguien más con un video personalizado de AfroBirthday: tu código de abajo te da un descuento y se aplica solo con el botón.",
    crossSellCta: "Pedir otro video",
    annualSubject: "¿Repetimos este año?",
    annualBody: "Hace un año de tu video de AfroBirthday: ¿celebramos de nuevo este año? Aquí tienes un código para ponértelo fácil; se aplica solo con el botón.",
    annualCta: "Crear mi próximo video",
    referralSubject: "Comparte la sorpresa y gana una recompensa",
    referralBody: "¿Te encantó tu video de AfroBirthday? Compártelo: tu código personal da a tus amigos {discount} en su primer pedido. Cuando lo usen, tú también recibirás una recompensa.",
    referralLinkIntro: "O simplemente envíales este enlace, el código se aplica solo:",
    referralCodeLabel: "Tu código de recomendación",
    referralRewardSubject: "¡Un amigo usó tu código!",
    referralRewardBody: "¡Buenas noticias! Un amigo acaba de usar tu código. Para agradecértelo, aquí tienes {discount} en tu próximo video de AfroBirthday.",
  },
  de: {
    confirmSubject: "Deine AfroBirthday-Bestellung ist bestätigt ({ref})",
    confirmTitle: "Danke für deine Bestellung 🎂",
    confirmIntro: "Wir haben deine Bestellung und deine Zahlung erhalten. Unsere Tänzer machen sich bereit!",
    details: "Bestelldetails",
    orderRef: "Bestellung",
    date: "Datum",
    total: "Gesamt",
    delivery: "Lieferung",
    deliveryStandard: "Standard (24–48 Std.)",
    deliveryExpress: "Express (12–24 Std.)",
    music: "Musik",
    musicCustom: "Dein Song",
    musicDefault: "Von uns ausgewählt",
    musicLink: "Song-Link",
    danceExtended: "Verlängerte Tanzversion",
    yes: "Ja",
    message: "Deine Nachricht",
    confirmOutro: "Du erhältst dein Video per E-Mail, sobald es fertig ist.",
    help: "Fragen? Antworte einfach auf diese E-Mail.",
    videoSubject: "Dein AfroBirthday-Video ist fertig 🎉 ({ref})",
    hi: "Hallo,",
    videoReady: "Dein personalisiertes Geburtstagsvideo ist fertig. Hier kannst du es ansehen und herunterladen:",
    videoCta: "Mein Video ansehen",
    videoFallback: "Falls der Button nicht funktioniert, kopiere diesen Link in deinen Browser:",
    videoReference: "Bestellnummer: {ref}. Wir freuen uns über dein Feedback — antworte einfach auf diese E-Mail.",
    thanks: "Danke, dass du AfroBirthday gewählt hast,",
    team: "Dein AfroBirthday-Team",
    footerTagline: "AfroBirthday — Personalisierte Geburtstagsvideos",
    footerReason: "Du erhältst diese E-Mail, weil du auf afrobirthday.com bestellt hast.",
    cartSubject: "Dein Geburtstagsvideo wartet auf dich 🎂",
    cartBody: "Du hast ein personalisiertes Geburtstagsvideo begonnen, aber die Bestellung nicht abgeschlossen. Mach genau dort weiter:",
    cartCta: "Bestellung abschließen",
    unsubscribe: "Von diesen E-Mails abmelden",
    promoCodeLabel: "Dein Code",
    discountPercent: "{value} % Rabatt",
    discountFixed: "{value} $ Rabatt",
    reviewSubject: "Wie hat dir dein AfroBirthday-Video gefallen?",
    reviewBody: "Wir hoffen, dein Geburtstagsvideo hat dir gefallen! Wenn du eine Minute hast, hilft uns eine kurze Bewertung sehr – so finden uns auch andere.",
    reviewCta: "Bewertung auf Trustpilot schreiben",
    crossSellSubject: "Steht bald wieder ein Geburtstag an?",
    crossSellBody: "Steht bald wieder ein Geburtstag an? Überrasche jemand anderen mit einem personalisierten AfroBirthday-Video – dein Code unten gibt dir Rabatt und wird über den Button automatisch angewendet.",
    crossSellCta: "Noch ein Video bestellen",
    annualSubject: "Feiern wir dieses Jahr wieder?",
    annualBody: "Dein AfroBirthday-Video ist jetzt ein Jahr her – feiern wir dieses Jahr wieder? Hier ist ein Code, der es dir leicht macht; er wird über den Button automatisch angewendet.",
    annualCta: "Mein nächstes Video erstellen",
    referralSubject: "Teile die Überraschung und werde belohnt",
    referralBody: "Hat dir dein AfroBirthday-Video gefallen? Teile es: Dein persönlicher Code gibt deinen Freunden {discount} auf ihre erste Bestellung. Wenn sie ihn nutzen, bekommst du auch eine Belohnung.",
    referralLinkIntro: "Oder schick ihnen einfach diesen Link – der Code wird automatisch angewendet:",
    referralCodeLabel: "Dein Empfehlungscode",
    referralRewardSubject: "Ein Freund hat deinen Code genutzt!",
    referralRewardBody: "Gute Nachrichten – ein Freund hat gerade deinen Empfehlungscode genutzt! Als Dankeschön bekommst du {discount} auf dein nächstes AfroBirthday-Video.",
  },
  it: {
    confirmSubject: "Il tuo ordine AfroBirthday è confermato ({ref})",
    confirmTitle: "Grazie per il tuo ordine 🎂",
    confirmIntro: "Abbiamo ricevuto il tuo ordine e il pagamento. I nostri ballerini si stanno preparando!",
    details: "Dettagli dell'ordine",
    orderRef: "Ordine",
    date: "Data",
    total: "Totale",
    delivery: "Consegna",
    deliveryStandard: "Standard (24–48 ore)",
    deliveryExpress: "Express (12–24 ore)",
    music: "Musica",
    musicCustom: "La tua canzone",
    musicDefault: "Scelta da noi",
    musicLink: "Link della canzone",
    danceExtended: "Versione ballo estesa",
    yes: "Sì",
    message: "Il tuo messaggio",
    confirmOutro: "Riceverai il video via email non appena sarà pronto.",
    help: "Hai bisogno di aiuto? Rispondi a questa email.",
    videoSubject: "Il tuo video AfroBirthday è pronto 🎉 ({ref})",
    hi: "Ciao,",
    videoReady: "Il tuo video di compleanno personalizzato è pronto. Puoi guardarlo e scaricarlo qui:",
    videoCta: "Guarda il mio video",
    videoFallback: "Se il pulsante non si apre, copia questo link nel browser:",
    videoReference: "Riferimento ordine: {ref}. Ci farebbe piacere un tuo parere — rispondi a questa email.",
    thanks: "Grazie per aver scelto AfroBirthday,",
    team: "Il team AfroBirthday",
    footerTagline: "AfroBirthday — Video di compleanno personalizzati",
    footerReason: "Ricevi questa email perché hai effettuato un ordine su afrobirthday.com.",
    cartSubject: "Il tuo video di compleanno ti aspetta 🎂",
    cartBody: "Hai iniziato un video di compleanno personalizzato ma non hai completato l'ordine. Riprendi da dove avevi lasciato:",
    cartCta: "Completa il mio ordine",
    unsubscribe: "Annulla l'iscrizione a queste email",
    promoCodeLabel: "Il tuo codice",
    discountPercent: "{value}% di sconto",
    discountFixed: "{value} $ di sconto",
    reviewSubject: "Ti è piaciuto il tuo video AfroBirthday?",
    reviewBody: "Speriamo che il tuo video di compleanno ti sia piaciuto! Se hai un minuto, una breve recensione ci aiuterebbe molto: così anche altri ci scoprono.",
    reviewCta: "Lascia una recensione su Trustpilot",
    crossSellSubject: "Un altro compleanno in arrivo?",
    crossSellBody: "Un altro compleanno in arrivo? Sorprendi qualcun altro con un video AfroBirthday personalizzato: il tuo codice qui sotto ti dà uno sconto e si applica da solo con il pulsante.",
    crossSellCta: "Ordina un altro video",
    annualSubject: "Festeggiamo di nuovo quest'anno?",
    annualBody: "È passato un anno dal tuo video AfroBirthday: festeggiamo di nuovo quest'anno? Ecco un codice per renderti tutto più facile; si applica da solo con il pulsante.",
    annualCta: "Crea il mio prossimo video",
    referralSubject: "Condividi la sorpresa e ricevi un premio",
    referralBody: "Ti è piaciuto il tuo video AfroBirthday? Condividilo: il tuo codice personale dà ai tuoi amici {discount} sul primo ordine. Quando lo usano, anche tu ricevi un premio.",
    referralLinkIntro: "Oppure invia loro questo link, il codice si applica da solo:",
    referralCodeLabel: "Il tuo codice amico",
    referralRewardSubject: "Un amico ha usato il tuo codice!",
    referralRewardBody: "Buone notizie: un amico ha appena usato il tuo codice! Per ringraziarti, ecco {discount} sul tuo prossimo video AfroBirthday.",
  },
  pt: {
    confirmSubject: "A sua encomenda AfroBirthday está confirmada ({ref})",
    confirmTitle: "Obrigado pela sua encomenda 🎂",
    confirmIntro: "Recebemos a sua encomenda e o pagamento. Os nossos dançarinos estão a preparar-se!",
    details: "Detalhes da encomenda",
    orderRef: "Encomenda",
    date: "Data",
    total: "Total",
    delivery: "Entrega",
    deliveryStandard: "Normal (24–48 h)",
    deliveryExpress: "Expresso (12–24 h)",
    music: "Música",
    musicCustom: "A sua música",
    musicDefault: "Escolhida por nós",
    musicLink: "Link da música",
    danceExtended: "Versão de dança alargada",
    yes: "Sim",
    message: "A sua mensagem",
    confirmOutro: "Vai receber o vídeo por email assim que estiver pronto.",
    help: "Precisa de ajuda? Basta responder a este email.",
    videoSubject: "O seu vídeo AfroBirthday está pronto 🎉 ({ref})",
    hi: "Olá,",
    videoReady: "O seu vídeo de aniversário personalizado está pronto. Pode vê-lo e descarregá-lo aqui:",
    videoCta: "Ver o meu vídeo",
    videoFallback: "Se o botão não abrir, copie este link para o navegador:",
    videoReference: "Referência da encomenda: {ref}. Adorávamos saber a sua opinião — responda a este email.",
    thanks: "Obrigado por escolher a AfroBirthday,",
    team: "A equipa AfroBirthday",
    footerTagline: "AfroBirthday — Vídeos de aniversário personalizados",
    footerReason: "Recebe este email porque fez uma encomenda em afrobirthday.com.",
    cartSubject: "O seu vídeo de aniversário está à espera 🎂",
    cartBody: "Começou um vídeo de aniversário personalizado mas não concluiu a encomenda. Continue onde parou:",
    cartCta: "Concluir a encomenda",
    unsubscribe: "Cancelar a subscrição destes e-mails",
    promoCodeLabel: "O seu código",
    discountPercent: "{value}% de desconto",
    discountFixed: "{value} $ de desconto",
    reviewSubject: "Gostou do seu vídeo AfroBirthday?",
    reviewBody: "Esperamos que tenha adorado o seu vídeo de aniversário! Se tiver um minuto, uma avaliação rápida ajuda-nos muito: assim outras pessoas descobrem-nos.",
    reviewCta: "Deixar uma avaliação no Trustpilot",
    crossSellSubject: "Vem aí outro aniversário?",
    crossSellBody: "Vem aí outro aniversário? Surpreenda mais alguém com um vídeo AfroBirthday personalizado: o seu código abaixo dá-lhe um desconto e aplica-se sozinho com o botão.",
    crossSellCta: "Encomendar outro vídeo",
    annualSubject: "Repetimos este ano?",
    annualBody: "Já passou um ano desde o seu vídeo AfroBirthday: celebramos outra vez este ano? Aqui tem um código para facilitar; aplica-se sozinho com o botão.",
    annualCta: "Criar o meu próximo vídeo",
    referralSubject: "Partilhe a surpresa e seja recompensado",
    referralBody: "Adorou o seu vídeo AfroBirthday? Partilhe-o: o seu código pessoal dá aos seus amigos {discount} na primeira encomenda. Quando o usarem, também recebe uma recompensa.",
    referralLinkIntro: "Ou envie-lhes simplesmente este link, o código aplica-se sozinho:",
    referralCodeLabel: "O seu código de indicação",
    referralRewardSubject: "Um amigo usou o seu código!",
    referralRewardBody: "Boas notícias: um amigo acabou de usar o seu código! Como agradecimento, aqui tem {discount} no seu próximo vídeo AfroBirthday.",
  },
  nl: {
    confirmSubject: "Je AfroBirthday-bestelling is bevestigd ({ref})",
    confirmTitle: "Bedankt voor je bestelling 🎂",
    confirmIntro: "We hebben je bestelling en betaling ontvangen. Onze dansers maken zich klaar!",
    details: "Bestelgegevens",
    orderRef: "Bestelling",
    date: "Datum",
    total: "Totaal",
    delivery: "Levering",
    deliveryStandard: "Standaard (24–48 uur)",
    deliveryExpress: "Express (12–24 uur)",
    music: "Muziek",
    musicCustom: "Jouw nummer",
    musicDefault: "Door ons gekozen",
    musicLink: "Link naar het nummer",
    danceExtended: "Verlengde dansversie",
    yes: "Ja",
    message: "Jouw bericht",
    confirmOutro: "Je ontvangt je video per e-mail zodra hij klaar is.",
    help: "Vragen? Beantwoord gewoon deze e-mail.",
    videoSubject: "Je AfroBirthday-video is klaar 🎉 ({ref})",
    hi: "Hallo,",
    videoReady: "Je persoonlijke verjaardagsvideo is klaar. Bekijk en download hem hier:",
    videoCta: "Bekijk mijn video",
    videoFallback: "Werkt de knop niet? Kopieer deze link in je browser:",
    videoReference: "Bestelnummer: {ref}. We horen graag wat je ervan vindt — beantwoord gewoon deze e-mail.",
    thanks: "Bedankt voor je keuze voor AfroBirthday,",
    team: "Het AfroBirthday-team",
    footerTagline: "AfroBirthday — Persoonlijke verjaardagsvideo's",
    footerReason: "Je ontvangt deze e-mail omdat je hebt besteld op afrobirthday.com.",
    cartSubject: "Je verjaardagsvideo wacht op je 🎂",
    cartBody: "Je bent begonnen aan een persoonlijke verjaardagsvideo maar hebt je bestelling niet afgerond. Ga verder waar je gebleven was:",
    cartCta: "Bestelling afronden",
    unsubscribe: "Afmelden voor deze e-mails",
    promoCodeLabel: "Je code",
    discountPercent: "{value}% korting",
    discountFixed: "{value} $ korting",
    reviewSubject: "Hoe vond je je AfroBirthday-video?",
    reviewBody: "We hopen dat je genoten hebt van je verjaardagsvideo! Heb je een minuutje? Een korte review helpt ons enorm, zo ontdekken anderen ons ook.",
    reviewCta: "Schrijf een review op Trustpilot",
    crossSellSubject: "Binnenkort weer een verjaardag?",
    crossSellBody: "Binnenkort weer een verjaardag? Verras iemand anders met een gepersonaliseerde AfroBirthday-video: je code hieronder geeft korting en wordt via de knop automatisch toegepast.",
    crossSellCta: "Nog een video bestellen",
    annualSubject: "Dit jaar weer feest?",
    annualBody: "Je AfroBirthday-video is alweer een jaar geleden: dit jaar weer feest? Hier is een code om het makkelijk te maken; hij wordt via de knop automatisch toegepast.",
    annualCta: "Mijn volgende video maken",
    referralSubject: "Deel de verrassing en word beloond",
    referralBody: "Vond je je AfroBirthday-video geweldig? Deel hem: je persoonlijke code geeft je vrienden {discount} op hun eerste bestelling. Gebruiken ze hem, dan krijg jij ook een beloning.",
    referralLinkIntro: "Of stuur ze gewoon deze link, de code wordt automatisch toegepast:",
    referralCodeLabel: "Je verwijzingscode",
    referralRewardSubject: "Een vriend heeft je code gebruikt!",
    referralRewardBody: "Goed nieuws: een vriend heeft net je verwijzingscode gebruikt! Als bedankje krijg je {discount} op je volgende AfroBirthday-video.",
  },
  ar: {
    confirmSubject: "تم تأكيد طلبك من AfroBirthday ({ref})",
    confirmTitle: "شكرًا لطلبك 🎂",
    confirmIntro: "استلمنا طلبك ودفعتك. راقصونا يستعدون الآن!",
    details: "تفاصيل الطلب",
    orderRef: "الطلب",
    date: "التاريخ",
    total: "الإجمالي",
    delivery: "التسليم",
    deliveryStandard: "عادي (24–48 ساعة)",
    deliveryExpress: "سريع (12–24 ساعة)",
    music: "الموسيقى",
    musicCustom: "أغنيتك",
    musicDefault: "من اختيارنا",
    musicLink: "رابط الأغنية",
    danceExtended: "نسخة رقص مطوّلة",
    yes: "نعم",
    message: "رسالتك",
    confirmOutro: "ستصلك الفيديو عبر البريد الإلكتروني فور جهوزه.",
    help: "تحتاج مساعدة؟ رد على هذه الرسالة.",
    videoSubject: "فيديو AfroBirthday الخاص بك جاهز 🎉 ({ref})",
    hi: "مرحبًا،",
    videoReady: "فيديو عيد الميلاد المخصص لك جاهز. يمكنك مشاهدته وتنزيله من هنا:",
    videoCta: "شاهد الفيديو",
    videoFallback: "إذا لم يعمل الزر، انسخ هذا الرابط في متصفحك:",
    videoReference: "رقم الطلب: {ref}. يسعدنا سماع رأيك — رد على هذه الرسالة.",
    thanks: "شكرًا لاختيارك AfroBirthday،",
    team: "فريق AfroBirthday",
    footerTagline: "AfroBirthday — فيديوهات أعياد ميلاد مخصصة",
    footerReason: "تتلقى هذه الرسالة لأنك قمت بطلب على afrobirthday.com.",
    cartSubject: "فيديو عيد الميلاد بانتظارك 🎂",
    cartBody: "بدأت إنشاء فيديو عيد ميلاد مخصص لكنك لم تُكمل طلبك. تابع من حيث توقفت:",
    cartCta: "إكمال طلبي",
    unsubscribe: "إلغاء الاشتراك في هذه الرسائل",
    promoCodeLabel: "رمزك",
    discountPercent: "خصم {value}%",
    discountFixed: "خصم {value} $",
    reviewSubject: "ما رأيك في فيديو AfroBirthday؟",
    reviewBody: "نتمنى أن يكون فيديو عيد الميلاد قد أعجبك! إن كان لديك دقيقة، فإن تقييمًا سريعًا يساعدنا كثيرًا ليتعرّف علينا آخرون.",
    reviewCta: "اكتب تقييمًا على Trustpilot",
    crossSellSubject: "هل يقترب عيد ميلاد آخر؟",
    crossSellBody: "هل يقترب عيد ميلاد آخر؟ فاجئ شخصًا آخر بفيديو AfroBirthday مخصص: رمزك أدناه يمنحك خصمًا ويُطبَّق تلقائيًا عند استخدام الزر.",
    crossSellCta: "اطلب فيديو آخر",
    annualSubject: "هل نحتفل من جديد هذا العام؟",
    annualBody: "مرّ عام على فيديو AfroBirthday الخاص بك: هل نحتفل من جديد هذا العام؟ إليك رمزًا يسهّل الأمر، ويُطبَّق تلقائيًا عند استخدام الزر.",
    annualCta: "أنشئ فيديوي التالي",
    referralSubject: "شارك المفاجأة واحصل على مكافأة",
    referralBody: "هل أعجبك فيديو AfroBirthday؟ شاركه: رمزك الشخصي يمنح أصدقاءك {discount} على طلبهم الأول. وعندما يستخدمونه، تحصل أنت أيضًا على مكافأة.",
    referralLinkIntro: "أو أرسل لهم هذا الرابط فقط، وسيُطبَّق الرمز تلقائيًا:",
    referralCodeLabel: "رمز الإحالة الخاص بك",
    referralRewardSubject: "استخدم أحد أصدقائك رمزك!",
    referralRewardBody: "خبر سار: استخدم أحد أصدقائك رمز الإحالة الخاص بك للتو! شكرًا لك، إليك {discount} على فيديو AfroBirthday القادم.",
  },
  hi: {
    confirmSubject: "आपका AfroBirthday ऑर्डर कन्फ़र्म हो गया ({ref})",
    confirmTitle: "आपके ऑर्डर के लिए धन्यवाद 🎂",
    confirmIntro: "हमें आपका ऑर्डर और भुगतान मिल गया है। हमारे डांसर तैयारी कर रहे हैं!",
    details: "ऑर्डर विवरण",
    orderRef: "ऑर्डर",
    date: "तारीख",
    total: "कुल",
    delivery: "डिलीवरी",
    deliveryStandard: "स्टैंडर्ड (24–48 घंटे)",
    deliveryExpress: "एक्सप्रेस (12–24 घंटे)",
    music: "संगीत",
    musicCustom: "आपका गाना",
    musicDefault: "हमारे द्वारा चुना गया",
    musicLink: "गाने का लिंक",
    danceExtended: "लंबा डांस वर्ज़न",
    yes: "हाँ",
    message: "आपका संदेश",
    confirmOutro: "वीडियो तैयार होते ही आपको ईमेल से मिल जाएगा।",
    help: "मदद चाहिए? बस इस ईमेल का जवाब दें।",
    videoSubject: "आपका AfroBirthday वीडियो तैयार है 🎉 ({ref})",
    hi: "नमस्ते,",
    videoReady: "आपका पर्सनलाइज़्ड जन्मदिन वीडियो तैयार है। आप इसे यहाँ देख और डाउनलोड कर सकते हैं:",
    videoCta: "मेरा वीडियो देखें",
    videoFallback: "अगर बटन न खुले, तो यह लिंक अपने ब्राउज़र में कॉपी करें:",
    videoReference: "ऑर्डर संदर्भ: {ref}. हमें आपकी राय जानकर खुशी होगी — बस इस ईमेल का जवाब दें।",
    thanks: "AfroBirthday चुनने के लिए धन्यवाद,",
    team: "AfroBirthday टीम",
    footerTagline: "AfroBirthday — पर्सनलाइज़्ड जन्मदिन वीडियो",
    footerReason: "आपको यह ईमेल इसलिए मिला क्योंकि आपने afrobirthday.com पर ऑर्डर किया था।",
    cartSubject: "आपका जन्मदिन वीडियो इंतज़ार कर रहा है 🎂",
    cartBody: "आपने एक पर्सनलाइज़्ड जन्मदिन वीडियो शुरू किया था लेकिन ऑर्डर पूरा नहीं किया। वहीं से जारी रखें:",
    cartCta: "मेरा ऑर्डर पूरा करें",
    unsubscribe: "इन ईमेल की सदस्यता छोड़ें",
    promoCodeLabel: "आपका कोड",
    discountPercent: "{value}% की छूट",
    discountFixed: "{value} $ की छूट",
    reviewSubject: "आपको अपना AfroBirthday वीडियो कैसा लगा?",
    reviewBody: "हमें उम्मीद है कि आपको अपना बर्थडे वीडियो पसंद आया! अगर आपके पास एक मिनट है, तो एक छोटा-सा रिव्यू हमारी बहुत मदद करेगा, ताकि दूसरे लोग भी हमें जान सकें।",
    reviewCta: "Trustpilot पर रिव्यू दें",
    crossSellSubject: "क्या एक और जन्मदिन आने वाला है?",
    crossSellBody: "क्या एक और जन्मदिन आने वाला है? किसी और को पर्सनलाइज़्ड AfroBirthday वीडियो से सरप्राइज़ दें: नीचे दिया गया आपका कोड छूट देता है और बटन से अपने-आप लागू हो जाता है।",
    crossSellCta: "एक और वीडियो ऑर्डर करें",
    annualSubject: "क्या इस साल फिर से जश्न मनाएं?",
    annualBody: "आपके AfroBirthday वीडियो को एक साल हो गया: क्या इस साल फिर से जश्न मनाएं? यह रहा एक कोड जो काम आसान कर दे; यह बटन से अपने-आप लागू हो जाता है।",
    annualCta: "मेरा अगला वीडियो बनाएं",
    referralSubject: "सरप्राइज़ शेयर करें, इनाम पाएं",
    referralBody: "आपको अपना AfroBirthday वीडियो पसंद आया? इसे शेयर करें: आपका पर्सनल कोड आपके दोस्तों को उनके पहले ऑर्डर पर {discount} देता है। जब वे इसका इस्तेमाल करेंगे, तो आपको भी इनाम मिलेगा।",
    referralLinkIntro: "या उन्हें बस यह लिंक भेजें, कोड अपने-आप लागू हो जाएगा:",
    referralCodeLabel: "आपका रेफ़रल कोड",
    referralRewardSubject: "एक दोस्त ने आपका कोड इस्तेमाल किया!",
    referralRewardBody: "अच्छी खबर: एक दोस्त ने अभी आपका रेफ़रल कोड इस्तेमाल किया! धन्यवाद के रूप में, आपके अगले AfroBirthday वीडियो पर {discount}।",
  },
  zh: {
    confirmSubject: "您的 AfroBirthday 订单已确认（{ref}）",
    confirmTitle: "感谢您的订单 🎂",
    confirmIntro: "我们已收到您的订单和付款。舞者们正在准备！",
    details: "订单详情",
    orderRef: "订单",
    date: "日期",
    total: "合计",
    delivery: "交付",
    deliveryStandard: "标准（24–48 小时）",
    deliveryExpress: "加急（12–24 小时）",
    music: "音乐",
    musicCustom: "您的歌曲",
    musicDefault: "由我们挑选",
    musicLink: "歌曲链接",
    danceExtended: "加长舞蹈版",
    yes: "是",
    message: "您的留言",
    confirmOutro: "视频完成后会第一时间通过电子邮件发送给您。",
    help: "需要帮助？直接回复此邮件即可。",
    videoSubject: "您的 AfroBirthday 视频已完成 🎉（{ref}）",
    hi: "您好，",
    videoReady: "您的专属生日视频已完成，可在此观看和下载：",
    videoCta: "观看我的视频",
    videoFallback: "如果按钮无法打开，请将此链接复制到浏览器：",
    videoReference: "订单编号：{ref}。欢迎反馈意见——直接回复此邮件即可。",
    thanks: "感谢您选择 AfroBirthday，",
    team: "AfroBirthday 团队",
    footerTagline: "AfroBirthday — 专属生日视频",
    footerReason: "您收到此邮件是因为您在 afrobirthday.com 下了订单。",
    cartSubject: "您的生日视频还在等您 🎂",
    cartBody: "您开始制作专属生日视频，但尚未完成订单。从上次离开的地方继续：",
    cartCta: "完成我的订单",
    unsubscribe: "退订此类邮件",
    promoCodeLabel: "您的优惠码",
    discountPercent: "{value}% 折扣",
    discountFixed: "{value} 美元优惠",
    reviewSubject: "您对 AfroBirthday 视频满意吗？",
    reviewBody: "希望您喜欢这段生日视频！如果您有一分钟，留下一条简短评价会对我们帮助很大，让更多人发现我们。",
    reviewCta: "在 Trustpilot 上留下评价",
    crossSellSubject: "又有生日快到了吗？",
    crossSellBody: "又有生日快到了吗？用一段定制的 AfroBirthday 视频给另一个人惊喜：下方优惠码可享折扣，点击按钮即自动使用。",
    crossSellCta: "再订一段视频",
    annualSubject: "今年再庆祝一次吗？",
    annualBody: "距离您的 AfroBirthday 视频已经一年了：今年再庆祝一次吗？这里有一个优惠码，点击按钮即自动使用。",
    annualCta: "制作我的下一段视频",
    referralSubject: "分享惊喜，赢取奖励",
    referralBody: "喜欢您的 AfroBirthday 视频吗？分享给朋友吧：您的专属优惠码让朋友首单享受 {discount}。朋友使用后，您也会获得奖励。",
    referralLinkIntro: "或者直接把这个链接发给他们，优惠码会自动使用：",
    referralCodeLabel: "您的推荐码",
    referralRewardSubject: "有朋友使用了您的推荐码！",
    referralRewardBody: "好消息：有朋友刚刚使用了您的推荐码！为表感谢，您的下一段 AfroBirthday 视频可享受 {discount}。",
  },
};

COPY.ru = {
  confirmSubject: "Ваш заказ AfroBirthday подтверждён ({ref})",
  confirmTitle: "Спасибо за заказ 🎂",
  confirmIntro: "Мы получили ваш заказ и оплату. Наши танцоры уже готовятся!",
  details: "Детали заказа",
  orderRef: "Заказ",
  date: "Дата",
  total: "Итого",
  delivery: "Доставка",
  deliveryStandard: "Стандарт (24–48 ч)",
  deliveryExpress: "Экспресс (12–24 ч)",
  music: "Музыка",
  musicCustom: "Ваша песня",
  musicDefault: "Выбираем мы",
  musicLink: "Ссылка на песню",
  danceExtended: "Расширенная версия танца",
  yes: "Да",
  message: "Ваше поздравление",
  confirmOutro: "Видео придёт вам на email, как только будет готово.",
  help: "Нужна помощь? Просто ответьте на это письмо.",
  videoSubject: "Ваше видео AfroBirthday готово 🎉 ({ref})",
  hi: "Здравствуйте!",
  videoReady: "Ваше персональное видео на день рождения готово. Посмотреть и скачать его можно здесь:",
  videoCta: "Смотреть видео",
  videoFallback: "Если кнопка не открывается, скопируйте эту ссылку в браузер:",
  videoReference: "Номер заказа: {ref}. Будем рады вашему отзыву — просто ответьте на это письмо.",
  thanks: "Спасибо, что выбрали AfroBirthday,",
  team: "Команда AfroBirthday",
  footerTagline: "AfroBirthday — персональные видео на день рождения",
  footerReason: "Вы получили это письмо, потому что оформили заказ на afrobirthday.com.",
  cartSubject: "Ваше видео на день рождения ждёт вас 🎂",
  cartBody: "Вы начали оформлять персональное видео на день рождения, но не завершили заказ. Продолжите с того места, где остановились:",
  cartCta: "Завершить заказ",
  unsubscribe: "Отписаться от этих писем",
  promoCodeLabel: "Ваш код",
  discountPercent: "скидка {value}%",
  discountFixed: "скидка {value} $",
  reviewSubject: "Как вам видео от AfroBirthday?",
  reviewBody: "Надеемся, вам понравилось видео на день рождения! Если у вас есть минутка, короткий отзыв очень нам поможет — так о нас узнают другие.",
  reviewCta: "Оставить отзыв на Trustpilot",
  crossSellSubject: "Скоро ещё один день рождения?",
  crossSellBody: "Скоро ещё один день рождения? Удивите кого-то ещё персональным видео от AfroBirthday: код ниже даёт скидку и применяется сам по кнопке.",
  crossSellCta: "Заказать ещё одно видео",
  annualSubject: "Отпразднуем снова в этом году?",
  annualBody: "Прошёл год с вашего видео от AfroBirthday — отпразднуем снова в этом году? Вот код, чтобы было проще; он применяется сам по кнопке.",
  annualCta: "Создать следующее видео",
  referralSubject: "Поделитесь сюрпризом и получите награду",
  referralBody: "Понравилось видео от AfroBirthday? Поделитесь им: ваш личный код даёт друзьям {discount} на первый заказ. Когда они им воспользуются, вы тоже получите награду.",
  referralLinkIntro: "Или просто отправьте им эту ссылку — код применится сам:",
  referralCodeLabel: "Ваш реферальный код",
  referralRewardSubject: "Друг воспользовался вашим кодом!",
  referralRewardBody: "Отличная новость: друг только что воспользовался вашим реферальным кодом! В благодарность — {discount} на ваше следующее видео от AfroBirthday.",
};

export function emailLocale(order: { locale?: string | null }): string {
  return order.locale && COPY[order.locale] ? order.locale : "en";
}

export function emailCopy(order: { locale?: string | null }): EmailCopy {
  return COPY[emailLocale(order)];
}

export function fill(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? "");
}
